// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLvTqBQkhRa3uvm_ugAjP1akGLXLo100g',
    appId: '1:224940977495:web:6c8745c26951b311762212',
    messagingSenderId: '224940977495',
    projectId: 'duan-17de7',
    authDomain: 'duan-17de7.firebaseapp.com',
    storageBucket: 'duan-17de7.firebasestorage.app',
    measurementId: 'G-2ZQ1LDYG2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYvUZtO93YQr97VXkj3-EjN1O7vTH3pFQ',
    appId: '1:224940977495:android:e0f17993b77cd83f762212',
    messagingSenderId: '224940977495',
    projectId: 'duan-17de7',
    storageBucket: 'duan-17de7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBERNEkZuJLErhDMfofoEiE61L6vCLKQx0',
    appId: '1:224940977495:ios:bca531557c8dfafe762212',
    messagingSenderId: '224940977495',
    projectId: 'duan-17de7',
    storageBucket: 'duan-17de7.firebasestorage.app',
    iosBundleId: 'com.example.duan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBERNEkZuJLErhDMfofoEiE61L6vCLKQx0',
    appId: '1:224940977495:ios:bca531557c8dfafe762212',
    messagingSenderId: '224940977495',
    projectId: 'duan-17de7',
    storageBucket: 'duan-17de7.firebasestorage.app',
    iosBundleId: 'com.example.duan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLvTqBQkhRa3uvm_ugAjP1akGLXLo100g',
    appId: '1:224940977495:web:d68a622e01d5db7b762212',
    messagingSenderId: '224940977495',
    projectId: 'duan-17de7',
    authDomain: 'duan-17de7.firebaseapp.com',
    storageBucket: 'duan-17de7.firebasestorage.app',
    measurementId: 'G-F5B5XZ5023',
  );
}
